"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-08 18:46:56.306928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector must be enabled before any table uses the `vector` column type below.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Enum('school', 'college', 'university', 'hostel', 'pg', name='orgtype'), nullable=False),
    sa.Column('plan', sa.Enum('starter', 'professional', 'enterprise', name='orgplan'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('audit_logs',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_table('departments',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_org_id'), 'departments', ['org_id'], unique=False)
    op.create_table('locations',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('parent_location_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('campus', 'building', 'floor', 'room', 'corridor', 'common_area', name='locationtype'), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_org_id'), 'locations', ['org_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('problem_submitted', 'problem_assigned', 'problem_in_progress', 'problem_resolved', 'problem_reopened', 'sla_breach', name='notificationtype'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('sla_rules',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('priority_bucket', sa.Enum('critical', 'high', 'medium', 'low', name='prioritybucket'), nullable=False),
    sa.Column('target_hours', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_rules_org_id'), 'sla_rules', ['org_id'], unique=False)
    op.create_table('problem_categories',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('default_department_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_categories_org_id'), 'problem_categories', ['org_id'], unique=False)
    op.create_table('user_org_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('reporter', 'resolver', 'admin', 'owner', name='userrole'), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('default_location_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_org_roles_org_id'), 'user_org_roles', ['org_id'], unique=False)
    op.create_index(op.f('ix_user_org_roles_user_id'), 'user_org_roles', ['user_id'], unique=False)
    op.create_table('problem_clusters',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('canonical_title', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', name='clusterstatus'), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('affected_users_estimate', sa.Integer(), nullable=False),
    sa.Column('recurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['problem_categories.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_clusters_org_id'), 'problem_clusters', ['org_id'], unique=False)
    op.create_index(op.f('ix_problem_clusters_status'), 'problem_clusters', ['status'], unique=False)
    op.create_table('problems',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('landmark', sa.String(length=300), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.Integer(), nullable=False),
    sa.Column('safety_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.Enum('reported', 'verified', 'assigned', 'in_progress', 'resolved', 'closed', 'reopened', name='problemstatus'), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('priority_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_breached', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['problem_categories.id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], ['problem_clusters.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_category_id'), 'problems', ['category_id'], unique=False)
    op.create_index(op.f('ix_problems_cluster_id'), 'problems', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_problems_location_id'), 'problems', ['location_id'], unique=False)
    op.create_index(op.f('ix_problems_org_id'), 'problems', ['org_id'], unique=False)
    op.create_index(op.f('ix_problems_priority_score'), 'problems', ['priority_score'], unique=False)
    op.create_index(op.f('ix_problems_reporter_id'), 'problems', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_problems_status'), 'problems', ['status'], unique=False)
    op.create_table('assignments',
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_problem_id'), 'assignments', ['problem_id'], unique=False)
    op.create_table('attachments',
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_problem_id'), 'attachments', ['problem_id'], unique=False)
    op.create_table('feedback',
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('resolved_confirmed', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_problem_id'), 'feedback', ['problem_id'], unique=False)
    op.create_table('problem_embeddings',
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_embeddings_problem_id'), 'problem_embeddings', ['problem_id'], unique=True)
    op.create_table('problem_relationships',
    sa.Column('problem_a_id', sa.UUID(), nullable=False),
    sa.Column('problem_b_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('relationship_type', sa.Enum('duplicate', 'related', 'recurring', name='relationshiptype'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['problem_a_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['problem_b_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_relationships_problem_a_id'), 'problem_relationships', ['problem_a_id'], unique=False)
    op.create_index(op.f('ix_problem_relationships_problem_b_id'), 'problem_relationships', ['problem_b_id'], unique=False)
    op.create_table('status_history',
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('reported', 'verified', 'assigned', 'in_progress', 'resolved', 'closed', 'reopened', name='problemstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('reported', 'verified', 'assigned', 'in_progress', 'resolved', 'closed', 'reopened', name='problemstatus'), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_history_problem_id'), 'status_history', ['problem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_history_problem_id'), table_name='status_history')
    op.drop_table('status_history')
    op.drop_index(op.f('ix_problem_relationships_problem_b_id'), table_name='problem_relationships')
    op.drop_index(op.f('ix_problem_relationships_problem_a_id'), table_name='problem_relationships')
    op.drop_table('problem_relationships')
    op.drop_index(op.f('ix_problem_embeddings_problem_id'), table_name='problem_embeddings')
    op.drop_table('problem_embeddings')
    op.drop_index(op.f('ix_feedback_problem_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_attachments_problem_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_assignments_problem_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_problems_status'), table_name='problems')
    op.drop_index(op.f('ix_problems_reporter_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_priority_score'), table_name='problems')
    op.drop_index(op.f('ix_problems_org_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_location_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_cluster_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_category_id'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_problem_clusters_status'), table_name='problem_clusters')
    op.drop_index(op.f('ix_problem_clusters_org_id'), table_name='problem_clusters')
    op.drop_table('problem_clusters')
    op.drop_index(op.f('ix_user_org_roles_user_id'), table_name='user_org_roles')
    op.drop_index(op.f('ix_user_org_roles_org_id'), table_name='user_org_roles')
    op.drop_table('user_org_roles')
    op.drop_index(op.f('ix_problem_categories_org_id'), table_name='problem_categories')
    op.drop_table('problem_categories')
    op.drop_index(op.f('ix_sla_rules_org_id'), table_name='sla_rules')
    op.drop_table('sla_rules')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_locations_org_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_departments_org_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
